version: '3'
services:
  app1:
    image: YOUR_CORE_APP
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - YOUR_ENV_VAR=http://app2:5000

  app2:
    image: YOUR_SECOND_APP
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
